spring:
  application:
    name: directrent-eureka
  devtools:
    restart:
      enabled: true
server:
  port: 8000

#eureka配置
eureka:
  client:
    #是否将自己注册到Eureka Server
    register-with-eureka: false
    #是否从Eureka Server获取注册信息
    fetch-registry: false
    #默认是http://localhost:8761/eureka
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/