spring:
  devtools:
    restart:
      enabled: true
  #数据源
  datasource:
    url: jdbc:mysql://rm-2vc14p10fe07522lheo.mysql.cn-chengdu.rds.aliyuncs.com:3306/directrent_house?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false&nullCatalogMeansCurrent=true
    username: directrent
    password: directrent
  redis:
    host: 114.55.28.2
    port: 6379
    password: youxin199855
    jedis:
      pool:
        max-active: 30 #连接池最大连接数（使用负值表示没有限制）
        max-wait: 10000 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 30 #连接池中的最大空闲连接
        min-idle: 10 #连接池中的最小空闲连接
    timeout: 30000 #连接超时时间（毫秒）