server:
  port: 9002
spring:
  application:
    name: directrent-gateway
  cloud:
    gateway:
      discovery:
        locator:
          #是否与服务注册于发现组件进行结合，通过 serviceId 转发到具体的服务实例。
          #默认为 false，设为 true 便开启通过服务中心的自动根据 serviceId 创建路由的功能。
          enabled: true
          #开启小写
          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://114.55.28.2:8000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
logging:
  level:
    org.springframework.cloud.gateway: debug
