spring:
  application:
    name: directrent-middle-service
  devtools:
    restart:
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://114.55.28.2:8000/eureka/