spring:
  application:
    name: directrent-middle-service
  devtools:
    restart:
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  rabbitmq:
    host: 114.55.28.2
    port: 5672
    virtual-host: /
    username: directrent
    password: directrent
    publisher-confirms: true #消息发送到交换器确认
    publisher-returns: true #消息发送到队列确认
server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://114.55.28.2:8000/eureka/
ftp:
  host: 114.55.28.2
  port: 21
  username: ftp
  password: qwerdf123
  base-path: /